# Generated by Django 2.1.1 on 2018-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
