# Generated by Django 2.1.1 on 2018-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0002_articel_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
